### ISSUE TITLE
Stucking on three purple dots

### ISSUE THREAD

**Issue by tamto6666** [saharmor/whisper-playground#4] opened 2022-10-17 09:52 UTC
Hi, I can't get it to work,

When I press "Start transcribing" button and say something, it keep loading and can't press to Stop the transcribing.

![image](https://user-images.githubusercontent.com/107444722/196147035-1dcbc3ef-f262-4d03-b465-ff77ebf7d7b0.png)

`$ sh install_playground.sh
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.41s.
Requirement already satisfied: wheel in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (0.37.1)

[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: python.exe -m pip install --upgrade pip
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113
Collecting git+https://github.com/openai/whisper.git (from -r requirements.txt (line 8))
  Cloning https://github.com/openai/whisper.git to c:\users\lnwry\appdata\local\temp\pip-req-build-kva5bjjp
  Running command git clone --filter=blob:none --quiet https://github.com/openai/whisper.git 'C:\Users\lnwry\AppData\Local\Temp\pip-req-build-kva5bjjp'
  Resolved https://github.com/openai/whisper.git to commit d18e9ea5dd2ca57c697e8e55f9e654f06ede25d0
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: numpy in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from -r requirements.txt (line 1)) (1.23.4)
Requirement already satisfied: tqdm in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from -r requirements.txt (line 2)) (4.64.1)
Requirement already satisfied: transformers>=4.19.0 in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from -r requirements.txt (line 3)) (4.23.1)
Requirement already satisfied: ffmpeg-python==0.2.0 in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from -r requirements.txt (line 4)) (0.2.0)
Requirement already satisfied: pyaudio in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from -r requirements.txt (line 5)) (0.2.12)
Requirement already satisfied: SpeechRecognition in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from -r requirements.txt (line 6)) (3.8.1)
Requirement already satisfied: pydub in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from -r requirements.txt (line 7)) (0.25.1)
Requirement already satisfied: torch in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from -r requirements.txt (line 10)) (1.12.1+cu113)
Requirement already satisfied: flask in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from -r requirements.txt (line 11)) (2.2.2)
Requirement already satisfied: flask_cors in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from -r requirements.txt (line 12)) (3.0.10)
Requirement already satisfied: future in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from ffmpeg-python==0.2.0->-r requirements.txt (line 4)) (0.18.2)
Requirement already satisfied: colorama in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from tqdm->-r requirements.txt (line 2)) (0.4.5)
Requirement already satisfied: regex!=2019.12.17 in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from transformers>=4.19.0->-r requirements.txt (line 3)) (2022.9.13)
Requirement already satisfied: pyyaml>=5.1 in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from transformers>=4.19.0->-r requirements.txt (line 3)) (6.0)
Requirement already satisfied: requests in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from transformers>=4.19.0->-r requirements.txt (line 3)) (2.28.1)
Requirement already satisfied: packaging>=20.0 in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from transformers>=4.19.0->-r requirements.txt (line 3)) (21.3)
Requirement already satisfied: filelock in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from transformers>=4.19.0->-r requirements.txt (line 3)) (3.8.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.10.0 in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from transformers>=4.19.0->-r requirements.txt (line 3)) (0.10.1)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from transformers>=4.19.0->-r requirements.txt (line 3)) (0.13.1)
Requirement already satisfied: more-itertools in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from whisper==1.0->-r requirements.txt (line 8)) (8.14.0)
Requirement already satisfied: typing-extensions in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from torch->-r requirements.txt (line 10)) (4.4.0)
Requirement already satisfied: itsdangerous>=2.0 in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from flask->-r requirements.txt (line 11)) (2.1.2)
Requirement already satisfied: click>=8.0 in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from flask->-r requirements.txt (line 11)) (8.1.3)
Requirement already satisfied: Jinja2>=3.0 in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from flask->-r requirements.txt (line 11)) (3.1.2)
Requirement already satisfied: Werkzeug>=2.2.2 in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from flask->-r requirements.txt (line 11)) (2.2.2)
Requirement already satisfied: Six in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from flask_cors->-r requirements.txt (line 12)) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from Jinja2>=3.0->flask->-r requirements.txt (line 11)) (2.1.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from packaging>=20.0->transformers>=4.19.0->-r requirements.txt (line 3)) (3.0.9)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from requests->transformers>=4.19.0->-r requirements.txt (line 3)) (1.26.12)
Requirement already satisfied: idna<4,>=2.5 in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from requests->transformers>=4.19.0->-r requirements.txt (line 3)) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from requests->transformers>=4.19.0->-r requirements.txt (line 3)) (2022.9.24)
Requirement already satisfied: charset-normalizer<3,>=2 in e:\vrchat mat\vtube\#whisper\whisper-playground\backend\venv\lib\site-packages (from requests->transformers>=4.19.0->-r requirements.txt (line 3)) (2.1.1)

[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: python.exe -m pip install --upgrade pip
`

**Comment by saharmor** [comment] 2023-01-11 13:08
Seems like a duplicate of this https://github.com/saharmor/whisper-playground/issues/6
Closing for now but feel free to reopen if the answer from the other issue doesn't help.

**Closed by saharmor** 2023-01-11 13:08 UTC
